
import React from 'react';
import { 
  HiRectangleStack,
  HiAcademicCap,
  HiBriefcase,
  HiBookOpen,
  HiBuildingLibrary,
  HiPencil,
  HiBookmark,
  HiNewspaper,
  HiQuestionMarkCircle,
  HiBeaker,
  HiCalculator,
  HiCube,
  HiPuzzlePiece,
  HiCodeBracket,
  HiCommandLine,
  HiCpuChip,
  HiServer,
  HiWifi,
  HiComputerDesktop,
  HiDevicePhoneMobile,
  HiTv,
  HiPrinter,
  HiCursorArrowRays,
  HiBattery100,
  HiBolt,
  HiBugAnt,
  HiChartBar,
  HiPresentationChartLine,
  HiTableCells,
  HiCurrencyDollar,
  HiBanknotes,
  HiCreditCard,
  HiScale,
  HiShoppingBag,
  HiTag,
  HiQrCode,
  HiCalendar,
  HiClock,
  HiArchiveBox,
  HiPaperClip,
  HiClipboardDocumentList,
  HiTrash,
  HiCog6Tooth,
  HiWrenchScrewdriver,
  HiAdjustmentsHorizontal,
  HiScissors,
  HiKey,
  HiLockClosed,
  HiShieldCheck,
  HiFingerPrint,
  HiIdentification,
  HiEye,
  HiChatBubbleLeftRight,
  HiEnvelope,
  HiInbox,
  HiUserGroup,
  HiShare,
  HiBell,
  HiMegaphone,
  HiMicrophone,
  HiSpeakerWave,
  HiMusicalNote,
  HiFilm,
  HiCamera,
  HiPhoto,
  HiFaceSmile,
  HiHandThumbUp,
  HiGift,
  HiCake,
  HiTrophy,
  HiGlobeAlt,
  HiGlobeAmericas,
  HiMap,
  HiMapPin,
  HiSun,
  HiMoon,
  HiCloud,
  HiTicket,
  HiFlag,
  HiTruck,
  HiPaperAirplane,
  HiRocketLaunch,
  HiLifebuoy,
  HiHome,
  HiExclamationTriangle,
  HiStar,
  HiHeart,
  HiSparkles,
  HiFire,
  HiLightBulb
} from 'react-icons/hi2';

// Map icon keys to components
export const ICON_MAP: Record<string, React.ElementType> = {
  // 1. Basic & Abstract
  stack: HiRectangleStack,
  academic: HiAcademicCap,
  briefcase: HiBriefcase,
  star: HiStar,
  heart: HiHeart,
  sparkles: HiSparkles,
  fire: HiFire,
  lightbulb: HiLightBulb,
  
  // 2. Education & Knowledge
  book: HiBookOpen,
  library: HiBuildingLibrary,
  pencil: HiPencil,
  bookmark: HiBookmark,
  news: HiNewspaper,
  question: HiQuestionMarkCircle,
  
  // 3. Science, Math & Tech
  beaker: HiBeaker,
  calc: HiCalculator,
  cube: HiCube,
  puzzle: HiPuzzlePiece,
  code: HiCodeBracket,
  terminal: HiCommandLine,
  cpu: HiCpuChip,
  server: HiServer,
  wifi: HiWifi,
  desktop: HiComputerDesktop,
  phone: HiDevicePhoneMobile,
  tv: HiTv,
  printer: HiPrinter,
  mouse: HiCursorArrowRays,
  battery: HiBattery100,
  bolt: HiBolt,
  bug: HiBugAnt,
  
  // 4. Business, Finance & Law
  chart: HiChartBar,
  presentation: HiPresentationChartLine,
  table: HiTableCells,
  dollar: HiCurrencyDollar,
  cash: HiBanknotes,
  card: HiCreditCard,
  scale: HiScale,
  bag: HiShoppingBag,
  tag: HiTag,
  qr: HiQrCode,
  
  // 5. Office, Tools & Utility
  calendar: HiCalendar,
  clock: HiClock,
  archive: HiArchiveBox,
  clip: HiPaperClip,
  clipboard: HiClipboardDocumentList,
  trash: HiTrash,
  gear: HiCog6Tooth,
  tools: HiWrenchScrewdriver,
  sliders: HiAdjustmentsHorizontal,
  scissors: HiScissors,
  key: HiKey,
  lock: HiLockClosed,
  shield: HiShieldCheck,
  fingerprint: HiFingerPrint,
  id: HiIdentification,
  eye: HiEye,
  
  // 6. Communication & Social
  chat: HiChatBubbleLeftRight,
  mail: HiEnvelope,
  inbox: HiInbox,
  users: HiUserGroup,
  share: HiShare,
  bell: HiBell,
  mega: HiMegaphone,
  mic: HiMicrophone,
  speaker: HiSpeakerWave,
  
  // 7. Arts, Media & Fun
  paint: HiPencil,
  music: HiMusicalNote,
  film: HiFilm,
  camera: HiCamera,
  photo: HiPhoto,
  smile: HiFaceSmile,
  like: HiHandThumbUp,
  gift: HiGift,
  cake: HiCake,
  trophy: HiTrophy,
  game: HiCube,
  
  // 8. Travel, Nature & World
  globe: HiGlobeAlt,
  globe_am: HiGlobeAmericas,
  map: HiMap,
  pin: HiMapPin,
  sun: HiSun,
  moon: HiMoon,
  cloud: HiCloud,
  ticket: HiTicket,
  flag: HiFlag,
  truck: HiTruck,
  plane: HiPaperAirplane,
  rocket: HiRocketLaunch,
  lifebuoy: HiLifebuoy,
  home: HiHome,
  warning: HiExclamationTriangle,
};

// Categorized/Ordered options for UI
export const ICON_OPTIONS = [
  // --- PRIMARY (Top visible 10) ---
  { key: 'stack', label: 'Mặc định' },
  { key: 'academic', label: 'Học tập' },
  { key: 'globe', label: 'Ngôn ngữ' },
  { key: 'calc', label: 'Toán học' },
  { key: 'beaker', label: 'Khoa học' },
  { key: 'code', label: 'Công nghệ' },
  { key: 'chart', label: 'Kinh tế' },
  { key: 'music', label: 'Nghệ thuật' },
  { key: 'cube', label: 'Tư duy' },
  { key: 'fire', label: 'Hot/Streak' },
  { key: 'star', label: 'Yêu thích' },
  { key: 'book', label: 'Sách vở' },
  
  // --- SECONDARY (Expanded) ---
  
  // Work & Productivity
  { key: 'briefcase', label: 'Công việc' },
  { key: 'calendar', label: 'Lịch trình' },
  { key: 'clock', label: 'Thời gian' },
  { key: 'presentation', label: 'Thuyết trình' },
  { key: 'clipboard', label: 'Danh sách' },
  { key: 'archive', label: 'Lưu trữ' },
  { key: 'tag', label: 'Nhãn' },
  { key: 'bookmark', label: 'Đánh dấu' },
  { key: 'table', label: 'Bảng/Data' },
  
  // Tech & Tools
  { key: 'desktop', label: 'Máy tính' },
  { key: 'phone', label: 'Điện thoại' },
  { key: 'cpu', label: 'CPU' },
  { key: 'terminal', label: 'Terminal' },
  { key: 'wifi', label: 'Kết nối' },
  { key: 'server', label: 'Server' },
  { key: 'bug', label: 'Debug/Lỗi' },
  { key: 'gear', label: 'Cài đặt' },
  { key: 'tools', label: 'Sửa chữa' },
  { key: 'sliders', label: 'Điều chỉnh' },
  { key: 'battery', label: 'Pin/Năng lượng' },
  { key: 'bolt', label: 'Điện/Lực' },
  { key: 'qr', label: 'QR Code' },
  
  // Communication
  { key: 'mail', label: 'Email' },
  { key: 'chat', label: 'Trò chuyện' },
  { key: 'mic', label: 'Ghi âm' },
  { key: 'mega', label: 'Thông báo' },
  { key: 'share', label: 'Chia sẻ' },
  
  // Money & Law
  { key: 'dollar', label: 'Tài chính' },
  { key: 'cash', label: 'Tiền mặt' },
  { key: 'card', label: 'Thẻ' },
  { key: 'bag', label: 'Mua sắm' },
  { key: 'scale', label: 'Luật pháp' },
  { key: 'id', label: 'ID/Thẻ' },
  
  // Life, Arts & Fun
  { key: 'lightbulb', label: 'Ý tưởng' },
  { key: 'paint', label: 'Vẽ/Design' },
  { key: 'camera', label: 'Chụp ảnh' },
  { key: 'film', label: 'Phim' },
  { key: 'smile', label: 'Vui vẻ' },
  { key: 'heart', label: 'Sức khỏe' },
  { key: 'gift', label: 'Quà tặng' },
  { key: 'cake', label: 'Sinh nhật' },
  { key: 'trophy', label: 'Thành tích' },
  { key: 'puzzle', label: 'Game' },
  { key: 'scissors', label: 'Thủ công' },
  
  // Security
  { key: 'key', label: 'Chìa khóa' },
  { key: 'lock', label: 'Khóa' },
  { key: 'shield', label: 'Bảo mật' },
  { key: 'fingerprint', label: 'Vân tay' },
  { key: 'eye', label: 'Theo dõi' },
  
  // Travel & Nature
  { key: 'rocket', label: 'Khởi nghiệp' },
  { key: 'plane', label: 'Du lịch' },
  { key: 'bike', label: 'Thể thao' },
  { key: 'truck', label: 'Vận chuyển' },
  { key: 'map', label: 'Bản đồ' },
  { key: 'pin', label: 'Địa điểm' },
  { key: 'sun', label: 'Sáng' },
  { key: 'moon', label: 'Tối' },
  
  // Misc
  { key: 'home', label: 'Nhà' },
  { key: 'library', label: 'Thư viện' },
  { key: 'question', label: 'Trợ giúp' },
  { key: 'warning', label: 'Lưu ý' },
];
